# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gerenciamentodenotas.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gerenciamentodenotas.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1agerenciamentodenotas.proto\"\x1c\n\rrequisicaoOpt\x12\x0b\n\x03opt\x18\x01 \x01(\x05\"b\n\x0frequisicaoNotas\x12\n\n\x02ra\x18\x01 \x01(\x05\x12\x16\n\x0e\x63od_disciplina\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\x12\x10\n\x08semestre\x18\x04 \x01(\x05\x12\x0c\n\x04nota\x18\x05 \x01(\x02\"*\n\x17requisicaoResponseNotas\x12\x0f\n\x07message\x18\x01 \x01(\t\"Q\n\x18requisicaoConsultaAlunos\x12\x16\n\x0e\x63od_disciplina\x18\x01 \x01(\t\x12\x0b\n\x03\x61no\x18\x02 \x01(\x05\x12\x10\n\x08semestre\x18\x03 \x01(\x05\"2\n\x05\x41luno\x12\n\n\x02ra\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07periodo\x18\x03 \x01(\x05\"J\n requisicaoResponseConsultaAlunos\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\x05\x61luno\x18\x02 \x03(\x0b\x32\x06.Alunob\x06proto3'
)




_REQUISICAOOPT = _descriptor.Descriptor(
  name='requisicaoOpt',
  full_name='requisicaoOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opt', full_name='requisicaoOpt.opt', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_REQUISICAONOTAS = _descriptor.Descriptor(
  name='requisicaoNotas',
  full_name='requisicaoNotas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ra', full_name='requisicaoNotas.ra', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cod_disciplina', full_name='requisicaoNotas.cod_disciplina', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ano', full_name='requisicaoNotas.ano', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='semestre', full_name='requisicaoNotas.semestre', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nota', full_name='requisicaoNotas.nota', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=158,
)


_REQUISICAORESPONSENOTAS = _descriptor.Descriptor(
  name='requisicaoResponseNotas',
  full_name='requisicaoResponseNotas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='requisicaoResponseNotas.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=202,
)


_REQUISICAOCONSULTAALUNOS = _descriptor.Descriptor(
  name='requisicaoConsultaAlunos',
  full_name='requisicaoConsultaAlunos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cod_disciplina', full_name='requisicaoConsultaAlunos.cod_disciplina', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ano', full_name='requisicaoConsultaAlunos.ano', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='semestre', full_name='requisicaoConsultaAlunos.semestre', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=285,
)


_ALUNO = _descriptor.Descriptor(
  name='Aluno',
  full_name='Aluno',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ra', full_name='Aluno.ra', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nome', full_name='Aluno.nome', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='periodo', full_name='Aluno.periodo', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=337,
)


_REQUISICAORESPONSECONSULTAALUNOS = _descriptor.Descriptor(
  name='requisicaoResponseConsultaAlunos',
  full_name='requisicaoResponseConsultaAlunos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='requisicaoResponseConsultaAlunos.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aluno', full_name='requisicaoResponseConsultaAlunos.aluno', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=413,
)

_REQUISICAORESPONSECONSULTAALUNOS.fields_by_name['aluno'].message_type = _ALUNO
DESCRIPTOR.message_types_by_name['requisicaoOpt'] = _REQUISICAOOPT
DESCRIPTOR.message_types_by_name['requisicaoNotas'] = _REQUISICAONOTAS
DESCRIPTOR.message_types_by_name['requisicaoResponseNotas'] = _REQUISICAORESPONSENOTAS
DESCRIPTOR.message_types_by_name['requisicaoConsultaAlunos'] = _REQUISICAOCONSULTAALUNOS
DESCRIPTOR.message_types_by_name['Aluno'] = _ALUNO
DESCRIPTOR.message_types_by_name['requisicaoResponseConsultaAlunos'] = _REQUISICAORESPONSECONSULTAALUNOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

requisicaoOpt = _reflection.GeneratedProtocolMessageType('requisicaoOpt', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOOPT,
  '__module__' : 'gerenciamentodenotas_pb2'
  # @@protoc_insertion_point(class_scope:requisicaoOpt)
  })
_sym_db.RegisterMessage(requisicaoOpt)

requisicaoNotas = _reflection.GeneratedProtocolMessageType('requisicaoNotas', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAONOTAS,
  '__module__' : 'gerenciamentodenotas_pb2'
  # @@protoc_insertion_point(class_scope:requisicaoNotas)
  })
_sym_db.RegisterMessage(requisicaoNotas)

requisicaoResponseNotas = _reflection.GeneratedProtocolMessageType('requisicaoResponseNotas', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAORESPONSENOTAS,
  '__module__' : 'gerenciamentodenotas_pb2'
  # @@protoc_insertion_point(class_scope:requisicaoResponseNotas)
  })
_sym_db.RegisterMessage(requisicaoResponseNotas)

requisicaoConsultaAlunos = _reflection.GeneratedProtocolMessageType('requisicaoConsultaAlunos', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOCONSULTAALUNOS,
  '__module__' : 'gerenciamentodenotas_pb2'
  # @@protoc_insertion_point(class_scope:requisicaoConsultaAlunos)
  })
_sym_db.RegisterMessage(requisicaoConsultaAlunos)

Aluno = _reflection.GeneratedProtocolMessageType('Aluno', (_message.Message,), {
  'DESCRIPTOR' : _ALUNO,
  '__module__' : 'gerenciamentodenotas_pb2'
  # @@protoc_insertion_point(class_scope:Aluno)
  })
_sym_db.RegisterMessage(Aluno)

requisicaoResponseConsultaAlunos = _reflection.GeneratedProtocolMessageType('requisicaoResponseConsultaAlunos', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAORESPONSECONSULTAALUNOS,
  '__module__' : 'gerenciamentodenotas_pb2'
  # @@protoc_insertion_point(class_scope:requisicaoResponseConsultaAlunos)
  })
_sym_db.RegisterMessage(requisicaoResponseConsultaAlunos)


# @@protoc_insertion_point(module_scope)
